/*
 * IRIS -- Intelligent Roadway Information System
 * Copyright (C) 2016-2020  Minnesota Department of Transportation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package us.mn.state.dot.tms.server.comm.incfeed;

import us.mn.state.dot.sched.DebugLog;
import us.mn.state.dot.tms.CommLink;
import us.mn.state.dot.tms.server.ControllerImpl;
import us.mn.state.dot.tms.server.comm.ThreadedPoller;
import static us.mn.state.dot.tms.utils.URIUtil.HTTP;

/**
 * Incident feed poller, which periodically retrieves incidents
 * generated by an external system via the specified URL.
 *
 * @author Douglas Lau
 */
public class IncFeedPoller extends ThreadedPoller<IncFeedProperty> {

	/** Incident feed debug log */
	static private final DebugLog INC_LOG = new DebugLog("inc_feed");

	/** Incident cache */
	private final IncidentCache cache;

	/** Create a new poller */
	public IncFeedPoller(CommLink link) {
		super(link, HTTP, INC_LOG);
		cache = new IncidentCache(link.getName(), INC_LOG);
	}

	/** Query incident feed */
	public void queryIncidents(ControllerImpl c) {
		addOp(new OpReadIncFeed(c, cache));
	}
}
