/*
 * IRIS -- Intelligent Roadway Information System
 * Copyright (C) 2000-2009  Minnesota Department of Transportation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package us.mn.state.dot.tms.server.comm.dmslite;

import java.io.EOFException;
import us.mn.state.dot.sonar.User;
import us.mn.state.dot.sonar.server.UserImpl;
import us.mn.state.dot.tms.DeviceRequest;
import us.mn.state.dot.tms.InvalidMessageException;
import us.mn.state.dot.tms.SignMessage;
import us.mn.state.dot.tms.SignMessageHelper;
import us.mn.state.dot.tms.DMSHelper;
import us.mn.state.dot.tms.server.ControllerImpl;
import us.mn.state.dot.tms.server.DMSImpl;
import us.mn.state.dot.tms.server.comm.AddressedMessage;
import us.mn.state.dot.tms.server.comm.DMSPoller;
import us.mn.state.dot.tms.server.comm.MessagePoller;
import us.mn.state.dot.tms.server.comm.Messenger;
import us.mn.state.dot.tms.server.comm.SocketMessenger;
import us.mn.state.dot.tms.utils.Log;

/**
 * DmsLitePoller. This class provides a DMS Poller developed
 * to support the Caltrans D10 IRIS implementation.
 *
 * @author Douglas Lau
 * @author Michael Darter
 */
public class DmsLitePoller extends MessagePoller implements DMSPoller {

	/** valid address range (inclusive) */
	static public final int MAX_ADDRESS = 255;
	static public final int MIN_ADDRESS = 1;

	/** Create a new dmslite poller */
	public DmsLitePoller(String n, Messenger m) {
		super(n, m);
		assert m instanceof SocketMessenger;
	}

	/**
	 * Create a new message for the specified controller. Called
	 * by parent MessagePoller.doPoll().
	 *
	 * @param c Associated controller.
	 * @return A newly created Message.
	 * @throws EOFException
	 */
	public AddressedMessage createMessage(ControllerImpl c)
		throws EOFException
	{
		//Log.finest("DmsLitePoller.createMessage() called.");
		return new Message(messenger.getOutputStream(c),
				   messenger.getInputStream(c));
	}

	/** Check if a drop address is valid */
	public boolean isAddressValid(int drop) {
		return ((drop >= MIN_ADDRESS) && (drop <= MAX_ADDRESS));
	}

	/**
	 * Send a new message to the sign. Called by DMSImpl.
	 * @throws InvalidMessageException
	 * @see DMSImpl,DMS
	 */
	public void sendMessage(DMSImpl dms, SignMessage m, User o)
		throws InvalidMessageException
	{
		if(dms == null || m == null || m.getBitmaps() == null)
			return;

		// dms isn't configured
		if(!dms.getConfigure())
			return;

		// Send blank if no message
		if(SignMessageHelper.isBlank(m)) {
			new OpBlank(dms, m, o).start();
			return;
		}

		// send message to field controller
		new OpMessage(dms, m, o).start();
	}

	/** Send a device request message to the sign, no user specified */
	public void sendRequest(DMSImpl dms, DeviceRequest r) {
		// user assumed to be IRIS
		User u = null;
		sendRequest(dms, r, u);
	}

	/** Send a device request message to the sign from a specific user */
	public void sendRequest(DMSImpl dms, DeviceRequest r, User u) {
		initialPoll(dms, r, u);
		_sendRequest(dms, r, u, false);
	}

	/** Perform an initial get-configuration and a get-status 
	 *  operation for periodically queriable DMS. */
	private void initialPoll(DMSImpl d, DeviceRequest r, User u) {
		if(d == null)
			return;
		// SEND_SETTINGS is sent on startup
		if(r == DeviceRequest.SEND_SETTINGS)
			if(!d.getConfigure()) {
				_sendRequest(d, DeviceRequest.
					QUERY_CONFIGURATION, u, false);
				_sendRequest(d, DeviceRequest.
					QUERY_MESSAGE, u, true);
			}
	}

	/** Send a device request message to the sign from a specific user */
	private void _sendRequest(DMSImpl dms, DeviceRequest r, User u, 
		boolean startup) 
	{
		if(dms == null)
			return;
		// handle requests
		if(r == DeviceRequest.QUERY_CONFIGURATION) {
			new OpQueryConfig(dms, u).start();
		} else if(r == DeviceRequest.QUERY_MESSAGE) {
			// generated by user and from TMSImpl periodically
			new OpQueryMsg(dms, u, r, startup).start();
		} else if(r == DeviceRequest.RESET_DEVICE) {
			new OpReset(dms, u).start();
		} else if(r == DeviceRequest.QUERY_STATUS) {
			// ignore
		} else if(r == DeviceRequest.SEND_SETTINGS) {
			// ignore
		} else if(r == DeviceRequest.RESET_MODEM) {
			// ignore
		} else if(r == DeviceRequest.QUERY_PIXEL_FAILURES) {
			// ignore
		} else {
			// ignore other requests
			Log.finest("DmsLitePoller.sendRequest(" + 
				dms.getName() +	"): ignored request r=" + 
				r + ", desc=" + r.description);
		}
	}
}
