/*
 * IRIS -- Intelligent Roadway Information System
 * Copyright (C) 2000-2016  Minnesota Department of Transportation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */
package us.mn.state.dot.tms.server.comm.msgfeed;

import us.mn.state.dot.sched.DebugLog;
import us.mn.state.dot.tms.server.ControllerImpl;
import us.mn.state.dot.tms.server.comm.ThreadedPoller;
import static us.mn.state.dot.tms.utils.URIUtil.HTTP;

/**
 * Msg feed poller, which periodically retrieves DMS messages
 * generated by an external system via the specified URL.
 *
 * @author Douglas Lau
 * @author Michael Darter
 */
public class MsgFeedPoller extends ThreadedPoller<MsgFeedProperty> {

	/** Feed debug log */
	static private final DebugLog FEED_LOG = new DebugLog("feed");

	/** Log a message to the debug log */
	static public void slog(String msg) {
		FEED_LOG.log(msg);
	}

	/** Create a new poller */
	public MsgFeedPoller(String n) {
		super(n, HTTP, FEED_LOG);
	}

	/** Query message feed */
	public void queryMessages(ControllerImpl c) {
		slog("creating OpReadMsgFeed: " + c);
		addOp(new OpReadMsgFeed(c, name));
	}
}
