SET SESSION AUTHORIZATION 'tms';

DROP TABLE monitor;

CREATE TABLE video_monitor (
	name TEXT PRIMARY KEY,
	description TEXT NOT NULL
);

REVOKE ALL ON TABLE video_monitor FROM PUBLIC;
GRANT SELECT ON TABLE video_monitor TO PUBLIC;
